import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Inter } from 'next/font/google'
import Footer from "./components/Footer";
 
const inter = Inter({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Easy Print",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-200 ${inter.className} h-screen flex flex-col`}>
        <Navbar />
        <div className="container mx-auto mb-auto">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
